/**
 * PM2 Ecosystem Configuration for VictoryKit
 * Production deployment with all 50 security tools
 */

module.exports = {
  apps: [
    // ===========================================
    // Core Services
    // ===========================================
    {
      name: 'api-gateway',
      script: 'server.js',
      cwd: './backend/shared-services/api-gateway',
      instances: 'max',
      exec_mode: 'cluster',
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 4000,
      },
      env_production: {
        NODE_ENV: 'production',
      },
      error_file: './logs/api-gateway-error.log',
      out_file: './logs/api-gateway-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'auth-service',
      script: 'server.js',
      cwd: './backend/shared-services/auth-service',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        PORT: 4001,
      },
      error_file: './logs/auth-service-error.log',
      out_file: './logs/auth-service-out.log',
      merge_logs: true,
      time: true,
    },

    // ===========================================
    // Security Tools (01-10)
    // ===========================================
    {
      name: 'fraudguard',
      script: 'server.js',
      cwd: './backend/tools/01-fraudguard/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4002 },
    },
    {
      name: 'intelliscout',
      script: 'server.js',
      cwd: './backend/tools/02-intelliscout/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4003 },
    },
    {
      name: 'threatradar',
      script: 'server.js',
      cwd: './backend/tools/03-threatradar/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4004 },
    },
    {
      name: 'malwarehunter',
      script: 'server.js',
      cwd: './backend/tools/04-malwarehunter/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '500M',
      env: { NODE_ENV: 'production', PORT: 4004 },
    },
    {
      name: 'phishguard',
      script: 'server.js',
      cwd: './backend/tools/05-phishguard/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4005 },
    },
    {
      name: 'vulnscan',
      script: 'server.js',
      cwd: './backend/tools/06-vulnscan/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '500M',
      env: { NODE_ENV: 'production', PORT: 4006 },
    },
    {
      name: 'pentestai',
      script: 'server.js',
      cwd: './backend/tools/07-pentestai/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '600M',
      env: { NODE_ENV: 'production', PORT: 4007 },
    },
    {
      name: 'securecode',
      script: 'server.js',
      cwd: './backend/tools/08-securecode/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '500M',
      env: { NODE_ENV: 'production', PORT: 4008 },
    },
    {
      name: 'compliancecheck',
      script: 'server.js',
      cwd: './backend/tools/09-compliancecheck/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4009 },
    },
    {
      name: 'dataguardian',
      script: 'server.js',
      cwd: './backend/tools/10-dataguardian/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4010 },
    },

    // ===========================================
    // Security Tools (11-20)
    // ===========================================
    {
      name: 'incidentresponse',
      script: 'server.js',
      cwd: './backend/tools/11-incidentresponse/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4011 },
    },
    {
      name: 'loganalyzer',
      script: 'server.js',
      cwd: './backend/tools/12-loganalyzer/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '500M',
      env: { NODE_ENV: 'production', PORT: 4012 },
    },
    {
      name: 'networkmonitor',
      script: 'server.js',
      cwd: './backend/tools/13-networkmonitor/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4013 },
    },
    {
      name: 'identityshield',
      script: 'server.js',
      cwd: './backend/tools/14-identityshield/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4014 },
    },
    {
      name: 'cryptovault',
      script: 'server.js',
      cwd: './backend/tools/15-cryptovault/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4015 },
    },
    {
      name: 'cloudsecure',
      script: 'server.js',
      cwd: './backend/tools/16-cloudsecure/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4016 },
    },
    {
      name: 'apisentry',
      script: 'server.js',
      cwd: './backend/tools/17-apisentry/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4017 },
    },
    {
      name: 'endpointarmor',
      script: 'server.js',
      cwd: './backend/tools/18-endpointarmor/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4018 },
    },
    {
      name: 'firewallpro',
      script: 'server.js',
      cwd: './backend/tools/19-firewallpro/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4019 },
    },
    {
      name: 'securityscore',
      script: 'server.js',
      cwd: './backend/tools/20-securityscore/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4020 },
    },

    // ===========================================
    // Security Tools (21-30)
    // ===========================================
    {
      name: 'riskradar',
      script: 'server.js',
      cwd: './backend/tools/21-riskradar/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4021 },
    },
    {
      name: 'assettracker',
      script: 'server.js',
      cwd: './backend/tools/22-assettracker/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4022 },
    },
    {
      name: 'accesscontrol',
      script: 'server.js',
      cwd: './backend/tools/23-accesscontrol/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4023 },
    },
    {
      name: 'audittrail',
      script: 'server.js',
      cwd: './backend/tools/24-audittrail/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4024 },
    },
    {
      name: 'dlpshield',
      script: 'server.js',
      cwd: './backend/tools/25-dlpshield/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4025 },
    },
    {
      name: 'emailsecurity',
      script: 'server.js',
      cwd: './backend/tools/26-emailsecurity/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4026 },
    },
    {
      name: 'siemconnect',
      script: 'server.js',
      cwd: './backend/tools/27-siemconnect/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4027 },
    },
    {
      name: 'soarengine',
      script: 'server.js',
      cwd: './backend/tools/28-soarengine/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4028 },
    },
    {
      name: 'threatintel',
      script: 'server.js',
      cwd: './backend/tools/29-threatintel/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4029 },
    },
    {
      name: 'policyengine',
      script: 'server.js',
      cwd: './backend/tools/30-policyengine/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4030 },
    },

    // ===========================================
    // Security Tools (31-40)
    // ===========================================
    {
      name: 'behavioranalytics',
      script: 'server.js',
      cwd: './backend/tools/31-behavioranalytics/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4031 },
    },
    {
      name: 'zerotrustai',
      script: 'server.js',
      cwd: './backend/tools/32-zerotrustai/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4032 },
    },
    {
      name: 'passwordvault',
      script: 'server.js',
      cwd: './backend/tools/33-passwordvault/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4033 },
    },
    {
      name: 'secretsmanager',
      script: 'server.js',
      cwd: './backend/tools/34-secretsmanager/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4034 },
    },
    {
      name: 'certificatemanager',
      script: 'server.js',
      cwd: './backend/tools/35-certificatemanager/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4035 },
    },
    {
      name: 'webfilter',
      script: 'server.js',
      cwd: './backend/tools/36-webfilter/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4036 },
    },
    {
      name: 'dnssecurity',
      script: 'server.js',
      cwd: './backend/tools/37-dnssecurity/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4037 },
    },
    {
      name: 'containerguard',
      script: 'server.js',
      cwd: './backend/tools/38-containerguard/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4038 },
    },
    {
      name: 'vpnguardian',
      script: 'server.js',
      cwd: './backend/tools/39-vpnguardian/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4039 },
    },
    {
      name: 'sdlcintegrator',
      script: 'server.js',
      cwd: './backend/tools/40-sdlcintegrator/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4040 },
    },

    // ===========================================
    // Security Tools (41-50)
    // ===========================================
    {
      name: 'iotsecure',
      script: 'server.js',
      cwd: './backend/tools/41-iotsecure/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4041 },
    },
    {
      name: 'mobiledefend',
      script: 'server.js',
      cwd: './backend/tools/42-mobiledefend/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4042 },
    },
    {
      name: 'backupguard',
      script: 'server.js',
      cwd: './backend/tools/43-backupguard/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4043 },
    },
    {
      name: 'drplan',
      script: 'server.js',
      cwd: './backend/tools/44-drplan/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4044 },
    },
    {
      name: 'privacyshield',
      script: 'server.js',
      cwd: './backend/tools/45-privacyshield/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4045 },
    },
    {
      name: 'gdprcompliance',
      script: 'server.js',
      cwd: './backend/tools/46-gdprcompliance/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4046 },
    },
    {
      name: 'hipaaguard',
      script: 'server.js',
      cwd: './backend/tools/47-hipaaguard/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4047 },
    },
    {
      name: 'pcidsscheck',
      script: 'server.js',
      cwd: './backend/tools/48-pcidsscheck/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4048 },
    },
    {
      name: 'bugbountyai',
      script: 'server.js',
      cwd: './backend/tools/49-bugbountyai/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4049 },
    },
    {
      name: 'securitydashboard',
      script: 'server.js',
      cwd: './backend/tools/50-securitydashboard/api',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '400M',
      env: { NODE_ENV: 'production', PORT: 4050 },
    },
  ],
};
